# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 17:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_merge_20171201_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='template_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/landing', location='/mnt/c/Users/gloompi/Desktop/works/filingroup/landing/templates/landing'), upload_to='', verbose_name='Template file (HTML file)'),
        ),
    ]
